// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/afudesk.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiAfudeskInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 860621179;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'afudesk_kopru',
        ioDirectory: 'kopru/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  String crateApiAfudeskCihazAdi();

  Future<GirdiOlayi> crateApiAfudeskGirdiOlayiDefault();

  Stream<HostOlayi> crateApiAfudeskHostBaslat({
    required String ad,
    required String parola,
    required bool upnp,
  });

  Future<void> crateApiAfudeskHostDurdur();

  Future<void> crateApiAfudeskHostKabul({
    required bool kontrol,
    required bool pano,
  });

  Future<void> crateApiAfudeskHostKes();

  Future<HostOlayi> crateApiAfudeskHostOlayiDefault();

  Future<void> crateApiAfudeskHostRed();

  Future<void> crateApiAfudeskInitApp();

  Stream<IzleyiciOlayi> crateApiAfudeskIzleyiciBaglan({
    required String kod,
    required String parola,
    required String ad,
  });

  Future<void> crateApiAfudeskIzleyiciGirdi({required GirdiOlayi g});

  Future<void> crateApiAfudeskIzleyiciKapat();

  Future<IzleyiciOlayi> crateApiAfudeskIzleyiciOlayiDefault();

  void crateApiAfudeskKareCizildi();

  String crateApiAfudeskSurum();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  String crateApiAfudeskCihazAdi() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskCihazAdiConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskCihazAdiConstMeta =>
      const TaskConstMeta(debugName: "cihaz_adi", argNames: []);

  @override
  Future<GirdiOlayi> crateApiAfudeskGirdiOlayiDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_girdi_olayi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskGirdiOlayiDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskGirdiOlayiDefaultConstMeta =>
      const TaskConstMeta(debugName: "girdi_olayi_default", argNames: []);

  @override
  Stream<HostOlayi> crateApiAfudeskHostBaslat({
    required String ad,
    required String parola,
    required bool upnp,
  }) {
    final olaylar = RustStreamSink<HostOlayi>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(ad, serializer);
            sse_encode_String(parola, serializer);
            sse_encode_bool(upnp, serializer);
            sse_encode_StreamSink_host_olayi_Sse(olaylar, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiAfudeskHostBaslatConstMeta,
          argValues: [ad, parola, upnp, olaylar],
          apiImpl: this,
        ),
      ),
    );
    return olaylar.stream;
  }

  TaskConstMeta get kCrateApiAfudeskHostBaslatConstMeta => const TaskConstMeta(
    debugName: "host_baslat",
    argNames: ["ad", "parola", "upnp", "olaylar"],
  );

  @override
  Future<void> crateApiAfudeskHostDurdur() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskHostDurdurConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskHostDurdurConstMeta =>
      const TaskConstMeta(debugName: "host_durdur", argNames: []);

  @override
  Future<void> crateApiAfudeskHostKabul({
    required bool kontrol,
    required bool pano,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(kontrol, serializer);
          sse_encode_bool(pano, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskHostKabulConstMeta,
        argValues: [kontrol, pano],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskHostKabulConstMeta => const TaskConstMeta(
    debugName: "host_kabul",
    argNames: ["kontrol", "pano"],
  );

  @override
  Future<void> crateApiAfudeskHostKes() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskHostKesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskHostKesConstMeta =>
      const TaskConstMeta(debugName: "host_kes", argNames: []);

  @override
  Future<HostOlayi> crateApiAfudeskHostOlayiDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_host_olayi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskHostOlayiDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskHostOlayiDefaultConstMeta =>
      const TaskConstMeta(debugName: "host_olayi_default", argNames: []);

  @override
  Future<void> crateApiAfudeskHostRed() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskHostRedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskHostRedConstMeta =>
      const TaskConstMeta(debugName: "host_red", argNames: []);

  @override
  Future<void> crateApiAfudeskInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<IzleyiciOlayi> crateApiAfudeskIzleyiciBaglan({
    required String kod,
    required String parola,
    required String ad,
  }) {
    final olaylar = RustStreamSink<IzleyiciOlayi>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(kod, serializer);
            sse_encode_String(parola, serializer);
            sse_encode_String(ad, serializer);
            sse_encode_StreamSink_izleyici_olayi_Sse(olaylar, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 10,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiAfudeskIzleyiciBaglanConstMeta,
          argValues: [kod, parola, ad, olaylar],
          apiImpl: this,
        ),
      ),
    );
    return olaylar.stream;
  }

  TaskConstMeta get kCrateApiAfudeskIzleyiciBaglanConstMeta =>
      const TaskConstMeta(
        debugName: "izleyici_baglan",
        argNames: ["kod", "parola", "ad", "olaylar"],
      );

  @override
  Future<void> crateApiAfudeskIzleyiciGirdi({required GirdiOlayi g}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_girdi_olayi(g, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskIzleyiciGirdiConstMeta,
        argValues: [g],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskIzleyiciGirdiConstMeta =>
      const TaskConstMeta(debugName: "izleyici_girdi", argNames: ["g"]);

  @override
  Future<void> crateApiAfudeskIzleyiciKapat() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskIzleyiciKapatConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskIzleyiciKapatConstMeta =>
      const TaskConstMeta(debugName: "izleyici_kapat", argNames: []);

  @override
  Future<IzleyiciOlayi> crateApiAfudeskIzleyiciOlayiDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_izleyici_olayi,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskIzleyiciOlayiDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskIzleyiciOlayiDefaultConstMeta =>
      const TaskConstMeta(debugName: "izleyici_olayi_default", argNames: []);

  @override
  void crateApiAfudeskKareCizildi() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskKareCizildiConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskKareCizildiConstMeta =>
      const TaskConstMeta(debugName: "kare_cizildi", argNames: []);

  @override
  String crateApiAfudeskSurum() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAfudeskSurumConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAfudeskSurumConstMeta =>
      const TaskConstMeta(debugName: "surum", argNames: []);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<HostOlayi> dco_decode_StreamSink_host_olayi_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<IzleyiciOlayi> dco_decode_StreamSink_izleyici_olayi_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  GirdiOlayi dco_decode_box_autoadd_girdi_olayi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_girdi_olayi(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  GirdiOlayi dco_decode_girdi_olayi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return GirdiOlayi(
      tur: dco_decode_String(arr[0]),
      x: dco_decode_f_64(arr[1]),
      y: dco_decode_f_64(arr[2]),
      ad: dco_decode_String(arr[3]),
      basili: dco_decode_bool(arr[4]),
      dx: dco_decode_i_32(arr[5]),
      dy: dco_decode_i_32(arr[6]),
      metin: dco_decode_String(arr[7]),
    );
  }

  @protected
  HostOlayi dco_decode_host_olayi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return HostOlayi(
      tur: dco_decode_String(arr[0]),
      kod: dco_decode_String(arr[1]),
      parola: dco_decode_String(arr[2]),
      erisim: dco_decode_String(arr[3]),
      adresler: dco_decode_list_String(arr[4]),
      ad: dco_decode_String(arr[5]),
      metin: dco_decode_String(arr[6]),
      kontrol: dco_decode_bool(arr[7]),
      pano: dco_decode_bool(arr[8]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  IzleyiciOlayi dco_decode_izleyici_olayi(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return IzleyiciOlayi(
      tur: dco_decode_String(arr[0]),
      rttMs: dco_decode_u_32(arr[1]),
      fps: dco_decode_u_32(arr[2]),
      ad: dco_decode_String(arr[3]),
      metin: dco_decode_String(arr[4]),
      kontrol: dco_decode_bool(arr[5]),
      pano: dco_decode_bool(arr[6]),
      genislik: dco_decode_u_32(arr[7]),
      yukseklik: dco_decode_u_32(arr[8]),
      rgba: dco_decode_list_prim_u_8_strict(arr[9]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<HostOlayi> sse_decode_StreamSink_host_olayi_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<IzleyiciOlayi> sse_decode_StreamSink_izleyici_olayi_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  GirdiOlayi sse_decode_box_autoadd_girdi_olayi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_girdi_olayi(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  GirdiOlayi sse_decode_girdi_olayi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tur = sse_decode_String(deserializer);
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    var var_ad = sse_decode_String(deserializer);
    var var_basili = sse_decode_bool(deserializer);
    var var_dx = sse_decode_i_32(deserializer);
    var var_dy = sse_decode_i_32(deserializer);
    var var_metin = sse_decode_String(deserializer);
    return GirdiOlayi(
      tur: var_tur,
      x: var_x,
      y: var_y,
      ad: var_ad,
      basili: var_basili,
      dx: var_dx,
      dy: var_dy,
      metin: var_metin,
    );
  }

  @protected
  HostOlayi sse_decode_host_olayi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tur = sse_decode_String(deserializer);
    var var_kod = sse_decode_String(deserializer);
    var var_parola = sse_decode_String(deserializer);
    var var_erisim = sse_decode_String(deserializer);
    var var_adresler = sse_decode_list_String(deserializer);
    var var_ad = sse_decode_String(deserializer);
    var var_metin = sse_decode_String(deserializer);
    var var_kontrol = sse_decode_bool(deserializer);
    var var_pano = sse_decode_bool(deserializer);
    return HostOlayi(
      tur: var_tur,
      kod: var_kod,
      parola: var_parola,
      erisim: var_erisim,
      adresler: var_adresler,
      ad: var_ad,
      metin: var_metin,
      kontrol: var_kontrol,
      pano: var_pano,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  IzleyiciOlayi sse_decode_izleyici_olayi(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tur = sse_decode_String(deserializer);
    var var_rttMs = sse_decode_u_32(deserializer);
    var var_fps = sse_decode_u_32(deserializer);
    var var_ad = sse_decode_String(deserializer);
    var var_metin = sse_decode_String(deserializer);
    var var_kontrol = sse_decode_bool(deserializer);
    var var_pano = sse_decode_bool(deserializer);
    var var_genislik = sse_decode_u_32(deserializer);
    var var_yukseklik = sse_decode_u_32(deserializer);
    var var_rgba = sse_decode_list_prim_u_8_strict(deserializer);
    return IzleyiciOlayi(
      tur: var_tur,
      rttMs: var_rttMs,
      fps: var_fps,
      ad: var_ad,
      metin: var_metin,
      kontrol: var_kontrol,
      pano: var_pano,
      genislik: var_genislik,
      yukseklik: var_yukseklik,
      rgba: var_rgba,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_host_olayi_Sse(
    RustStreamSink<HostOlayi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_host_olayi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_izleyici_olayi_Sse(
    RustStreamSink<IzleyiciOlayi> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_izleyici_olayi,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_girdi_olayi(
    GirdiOlayi self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_girdi_olayi(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_girdi_olayi(GirdiOlayi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tur, serializer);
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
    sse_encode_String(self.ad, serializer);
    sse_encode_bool(self.basili, serializer);
    sse_encode_i_32(self.dx, serializer);
    sse_encode_i_32(self.dy, serializer);
    sse_encode_String(self.metin, serializer);
  }

  @protected
  void sse_encode_host_olayi(HostOlayi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tur, serializer);
    sse_encode_String(self.kod, serializer);
    sse_encode_String(self.parola, serializer);
    sse_encode_String(self.erisim, serializer);
    sse_encode_list_String(self.adresler, serializer);
    sse_encode_String(self.ad, serializer);
    sse_encode_String(self.metin, serializer);
    sse_encode_bool(self.kontrol, serializer);
    sse_encode_bool(self.pano, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_izleyici_olayi(IzleyiciOlayi self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.tur, serializer);
    sse_encode_u_32(self.rttMs, serializer);
    sse_encode_u_32(self.fps, serializer);
    sse_encode_String(self.ad, serializer);
    sse_encode_String(self.metin, serializer);
    sse_encode_bool(self.kontrol, serializer);
    sse_encode_bool(self.pano, serializer);
    sse_encode_u_32(self.genislik, serializer);
    sse_encode_u_32(self.yukseklik, serializer);
    sse_encode_list_prim_u_8_strict(self.rgba, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
