// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `host_dto`, `host_komut`, `izleyici_pompala`, `kayitlar`, `rt`, `veri`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Uygulama açılışında çağrılır: kimlik ve kayıtlı cihazlar bu klasörde saklanır.
void veriKlasoruAyarla({required String yol}) =>
    RustLib.instance.api.crateApiAfudeskVeriKlasoruAyarla(yol: yol);

/// Bu cihazın kod olmadan bağlanabileceği bilgisayarlar (en son görülen önce).
List<KayitliCihaz> kayitliCihazlar() =>
    RustLib.instance.api.crateApiAfudeskKayitliCihazlar();

/// İzleyici: kaydı unut (karşı tarafa haber verilmez).
void kayitliUnut({required String kimlik}) =>
    RustLib.instance.api.crateApiAfudeskKayitliUnut(kimlik: kimlik);

/// Bu bilgisayara kod olmadan bağlanabilen cihazlar (en son görülen önce).
List<KayitliCihaz> guvenilenCihazlar() =>
    RustLib.instance.api.crateApiAfudeskGuvenilenCihazlar();

/// Host: güvenilen cihazı kaldır; o cihaz bir dahaki sefere kod gerektiğini öğrenir.
void guvenilenKaldir({required String kimlik}) =>
    RustLib.instance.api.crateApiAfudeskGuvenilenKaldir(kimlik: kimlik);

/// Bu bilgisayarın görünen adı (karşı tarafa gösterilir).
String cihazAdi() => RustLib.instance.api.crateApiAfudeskCihazAdi();

String surum() => RustLib.instance.api.crateApiAfudeskSurum();

/// Uygulama açıkken arka planda çalışan host'u başlatır (kayıtlı cihazlar onayla bağlanabilir);
/// kodla bağlantı `host_kod_ac(true)` ile ("Bağlantı ver" ekranı) açılır. Önceki host durdurulur.
Stream<HostOlayi> hostBaslat({
  required String ad,
  required String parola,
  required bool upnp,
}) => RustLib.instance.api.crateApiAfudeskHostBaslat(
  ad: ad,
  parola: parola,
  upnp: upnp,
);

Future<void> hostKabul({
  required bool kontrol,
  required bool pano,
  required bool dosya,
  required bool oyunKolu,
}) => RustLib.instance.api.crateApiAfudeskHostKabul(
  kontrol: kontrol,
  pano: pano,
  dosya: dosya,
  oyunKolu: oyunKolu,
);

Future<void> hostRed() => RustLib.instance.api.crateApiAfudeskHostRed();

Future<void> hostKes() => RustLib.instance.api.crateApiAfudeskHostKes();

/// "Bağlantı ver" ekranı açılınca true, kapanınca false: kod yalnız ekran açıkken geçerli.
void hostKodAc({required bool acik}) =>
    RustLib.instance.api.crateApiAfudeskHostKodAc(acik: acik);

Future<void> hostDurdur() => RustLib.instance.api.crateApiAfudeskHostDurdur();

/// Koda bağlan. Her şey (hatalar dahil: `tur = "hata"`) `olaylar` akışından gelir.
/// Not: FRB akış fonksiyonunun Err dönüşü akışa değil yakalanmamış istisnaya gider;
/// bu yüzden hata olay olarak yazılır.
Stream<IzleyiciOlayi> izleyiciBaglan({
  required String kod,
  required String parola,
  required String ad,
}) => RustLib.instance.api.crateApiAfudeskIzleyiciBaglan(
  kod: kod,
  parola: parola,
  ad: ad,
);

/// Kayıtlı bilgisayara kod ve parola olmadan bağlan (karşı taraf yine onay verir).
Stream<IzleyiciOlayi> izleyiciKayitliBaglan({
  required String kimlik,
  required String ad,
}) => RustLib.instance.api.crateApiAfudeskIzleyiciKayitliBaglan(
  kimlik: kimlik,
  ad: ad,
);

/// Dart kareyi ekrana çizdiğinde çağırır.
void kareCizildi() => RustLib.instance.api.crateApiAfudeskKareCizildi();

Future<void> izleyiciGirdi({required GirdiOlayi g}) =>
    RustLib.instance.api.crateApiAfudeskIzleyiciGirdi(g: g);

/// Dart'tan gelen oyun kolu durumunu mevcut datagram yoluna verir; sıra numarasını Rust atar.
Future<void> izleyiciKol({
  required int slot,
  required int dugmeler,
  required int solX,
  required int solY,
  required int sagX,
  required int sagY,
  required int solTetik,
  required int sagTetik,
}) => RustLib.instance.api.crateApiAfudeskIzleyiciKol(
  slot: slot,
  dugmeler: dugmeler,
  solX: solX,
  solY: solY,
  sagX: sagX,
  sagY: sagY,
  solTetik: solTetik,
  sagTetik: sagTetik,
);

/// Dosyayı karşı tarafa gönderir; ilerleme/sonuç izleyici akışına `tur = "dosya"` olarak gelir.
Future<void> izleyiciDosyaGonder({required String yol}) =>
    RustLib.instance.api.crateApiAfudeskIzleyiciDosyaGonder(yol: yol);

Future<void> izleyiciKapat() =>
    RustLib.instance.api.crateApiAfudeskIzleyiciKapat();

/// Girdi. `tur`: konum | fare | kaydir | tus | metin.
class GirdiOlayi {
  final String tur;
  final double x;
  final double y;

  /// fare: sol | sag | orta; tus: tuş adı.
  final String ad;
  final bool basili;
  final int dx;
  final int dy;
  final String metin;

  const GirdiOlayi({
    required this.tur,
    required this.x,
    required this.y,
    required this.ad,
    required this.basili,
    required this.dx,
    required this.dy,
    required this.metin,
  });

  static Future<GirdiOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskGirdiOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      x.hashCode ^
      y.hashCode ^
      ad.hashCode ^
      basili.hashCode ^
      dx.hashCode ^
      dy.hashCode ^
      metin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GirdiOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          x == other.x &&
          y == other.y &&
          ad == other.ad &&
          basili == other.basili &&
          dx == other.dx &&
          dy == other.dy &&
          metin == other.metin;
}

/// Host olayı. `tur`: hazir | istek | baglandi | koptu | hata | dosya | uyari | yeniden.
class HostOlayi {
  final String tur;
  final String kod;
  final String parola;
  final String erisim;
  final List<String> adresler;
  final String ad;
  final String metin;
  final bool kontrol;
  final bool pano;

  /// baglandi: dosya alma izni.
  final bool dosya;

  /// dosya: alınan dosyanın tam yolu.
  final String yol;
  final bool oyunKolu;

  /// istek: kayıtlı cihaz (kod olmadan) bağlanmak istiyor.
  final bool kayitli;

  const HostOlayi({
    required this.tur,
    required this.kod,
    required this.parola,
    required this.erisim,
    required this.adresler,
    required this.ad,
    required this.metin,
    required this.kontrol,
    required this.pano,
    required this.dosya,
    required this.yol,
    required this.oyunKolu,
    required this.kayitli,
  });

  static Future<HostOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskHostOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      kod.hashCode ^
      parola.hashCode ^
      erisim.hashCode ^
      adresler.hashCode ^
      ad.hashCode ^
      metin.hashCode ^
      kontrol.hashCode ^
      pano.hashCode ^
      dosya.hashCode ^
      yol.hashCode ^
      oyunKolu.hashCode ^
      kayitli.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          kod == other.kod &&
          parola == other.parola &&
          erisim == other.erisim &&
          adresler == other.adresler &&
          ad == other.ad &&
          metin == other.metin &&
          kontrol == other.kontrol &&
          pano == other.pano &&
          dosya == other.dosya &&
          yol == other.yol &&
          oyunKolu == other.oyunKolu &&
          kayitli == other.kayitli;
}

/// İzleyici olayı. `tur`: bekliyor | kabul | kare | istatistik (metin = yol) | yeniden | kaydedildi |
/// koptu | hata | pano | dosya.
class IzleyiciOlayi {
  final String tur;
  final int rttMs;
  final int fps;
  final int gecikmeMs;
  final String ad;
  final String metin;
  final bool kontrol;
  final bool pano;
  final int genislik;
  final int yukseklik;
  final Uint8List rgba;

  /// kabul: dosya gönderme izni.
  final bool dosya;
  final bool oyunKolu;

  /// dosya: gönderilen/toplam bayt; `bitti` ise `metin` boşsa başarılı, doluysa hata.
  final BigInt gonderilen;
  final BigInt toplam;
  final bool bitti;
  final int slot;
  final int buyuk;
  final int kucuk;

  const IzleyiciOlayi({
    required this.tur,
    required this.rttMs,
    required this.fps,
    required this.gecikmeMs,
    required this.ad,
    required this.metin,
    required this.kontrol,
    required this.pano,
    required this.genislik,
    required this.yukseklik,
    required this.rgba,
    required this.dosya,
    required this.oyunKolu,
    required this.gonderilen,
    required this.toplam,
    required this.bitti,
    required this.slot,
    required this.buyuk,
    required this.kucuk,
  });

  static Future<IzleyiciOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskIzleyiciOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      rttMs.hashCode ^
      fps.hashCode ^
      gecikmeMs.hashCode ^
      ad.hashCode ^
      metin.hashCode ^
      kontrol.hashCode ^
      pano.hashCode ^
      genislik.hashCode ^
      yukseklik.hashCode ^
      rgba.hashCode ^
      dosya.hashCode ^
      oyunKolu.hashCode ^
      gonderilen.hashCode ^
      toplam.hashCode ^
      bitti.hashCode ^
      slot.hashCode ^
      buyuk.hashCode ^
      kucuk.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IzleyiciOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          rttMs == other.rttMs &&
          fps == other.fps &&
          gecikmeMs == other.gecikmeMs &&
          ad == other.ad &&
          metin == other.metin &&
          kontrol == other.kontrol &&
          pano == other.pano &&
          genislik == other.genislik &&
          yukseklik == other.yukseklik &&
          rgba == other.rgba &&
          dosya == other.dosya &&
          oyunKolu == other.oyunKolu &&
          gonderilen == other.gonderilen &&
          toplam == other.toplam &&
          bitti == other.bitti &&
          slot == other.slot &&
          buyuk == other.buyuk &&
          kucuk == other.kucuk;
}

/// Kayıtlı/güvenilen cihaz (listede yalnız ad ve son görülme gösterilir).
class KayitliCihaz {
  /// İç kimlik: yalnız Bağlan/Unut/Kaldır çağrılarında kullanılır, gösterilmez.
  final String kimlik;
  final String ad;

  /// Unix saniye.
  final PlatformInt64 sonGorulme;

  const KayitliCihaz({
    required this.kimlik,
    required this.ad,
    required this.sonGorulme,
  });

  static Future<KayitliCihaz> default_() =>
      RustLib.instance.api.crateApiAfudeskKayitliCihazDefault();

  @override
  int get hashCode => kimlik.hashCode ^ ad.hashCode ^ sonGorulme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KayitliCihaz &&
          runtimeType == other.runtimeType &&
          kimlik == other.kimlik &&
          ad == other.ad &&
          sonGorulme == other.sonGorulme;
}
