// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `host_dto`, `host_komut`, `rt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Bu bilgisayarın görünen adı (karşı tarafa gösterilir).
String cihazAdi() => RustLib.instance.api.crateApiAfudeskCihazAdi();

String surum() => RustLib.instance.api.crateApiAfudeskSurum();

/// Bağlantı ver: sunucuyu açar, olayları `olaylar` akışına yazar. Önceki host varsa durdurulur.
Stream<HostOlayi> hostBaslat({
  required String ad,
  required String parola,
  required bool upnp,
}) => RustLib.instance.api.crateApiAfudeskHostBaslat(
  ad: ad,
  parola: parola,
  upnp: upnp,
);

Future<void> hostKabul({required bool kontrol}) =>
    RustLib.instance.api.crateApiAfudeskHostKabul(kontrol: kontrol);

Future<void> hostRed() => RustLib.instance.api.crateApiAfudeskHostRed();

Future<void> hostKes() => RustLib.instance.api.crateApiAfudeskHostKes();

Future<void> hostDurdur() => RustLib.instance.api.crateApiAfudeskHostDurdur();

/// Koda bağlan. Başarısızlık (yanlış parola, ulaşılamıyor...) hata olarak döner;
/// bağlandıktan sonraki her şey `olaylar` akışından gelir.
Stream<IzleyiciOlayi> izleyiciBaglan({
  required String kod,
  required String parola,
  required String ad,
}) => RustLib.instance.api.crateApiAfudeskIzleyiciBaglan(
  kod: kod,
  parola: parola,
  ad: ad,
);

/// Dart kareyi ekrana çizdiğinde çağırır.
void kareCizildi() => RustLib.instance.api.crateApiAfudeskKareCizildi();

Future<void> izleyiciGirdi({required GirdiOlayi g}) =>
    RustLib.instance.api.crateApiAfudeskIzleyiciGirdi(g: g);

Future<void> izleyiciKapat() =>
    RustLib.instance.api.crateApiAfudeskIzleyiciKapat();

/// Girdi. `tur`: konum | fare | kaydir | tus | metin.
class GirdiOlayi {
  final String tur;
  final double x;
  final double y;

  /// fare: sol | sag | orta; tus: tuş adı.
  final String ad;
  final bool basili;
  final int dx;
  final int dy;
  final String metin;

  const GirdiOlayi({
    required this.tur,
    required this.x,
    required this.y,
    required this.ad,
    required this.basili,
    required this.dx,
    required this.dy,
    required this.metin,
  });

  static Future<GirdiOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskGirdiOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      x.hashCode ^
      y.hashCode ^
      ad.hashCode ^
      basili.hashCode ^
      dx.hashCode ^
      dy.hashCode ^
      metin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GirdiOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          x == other.x &&
          y == other.y &&
          ad == other.ad &&
          basili == other.basili &&
          dx == other.dx &&
          dy == other.dy &&
          metin == other.metin;
}

/// Host olayı. `tur`: hazir | istek | baglandi | koptu | hata.
class HostOlayi {
  final String tur;
  final String kod;
  final String parola;
  final String erisim;
  final List<String> adresler;
  final String ad;
  final String metin;
  final bool kontrol;

  const HostOlayi({
    required this.tur,
    required this.kod,
    required this.parola,
    required this.erisim,
    required this.adresler,
    required this.ad,
    required this.metin,
    required this.kontrol,
  });

  static Future<HostOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskHostOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      kod.hashCode ^
      parola.hashCode ^
      erisim.hashCode ^
      adresler.hashCode ^
      ad.hashCode ^
      metin.hashCode ^
      kontrol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          kod == other.kod &&
          parola == other.parola &&
          erisim == other.erisim &&
          adresler == other.adresler &&
          ad == other.ad &&
          metin == other.metin &&
          kontrol == other.kontrol;
}

/// İzleyici olayı. `tur`: bekliyor | kabul | kare | koptu.
class IzleyiciOlayi {
  final String tur;
  final String ad;
  final String metin;
  final bool kontrol;
  final int genislik;
  final int yukseklik;
  final Uint8List rgba;

  const IzleyiciOlayi({
    required this.tur,
    required this.ad,
    required this.metin,
    required this.kontrol,
    required this.genislik,
    required this.yukseklik,
    required this.rgba,
  });

  static Future<IzleyiciOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskIzleyiciOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      ad.hashCode ^
      metin.hashCode ^
      kontrol.hashCode ^
      genislik.hashCode ^
      yukseklik.hashCode ^
      rgba.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IzleyiciOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          ad == other.ad &&
          metin == other.metin &&
          kontrol == other.kontrol &&
          genislik == other.genislik &&
          yukseklik == other.yukseklik &&
          rgba == other.rgba;
}
