// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `host_dto`, `host_komut`, `rt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

/// Bu bilgisayarın görünen adı (karşı tarafa gösterilir).
String cihazAdi() => RustLib.instance.api.crateApiAfudeskCihazAdi();

String surum() => RustLib.instance.api.crateApiAfudeskSurum();

/// Bağlantı ver: sunucuyu açar, olayları `olaylar` akışına yazar. Önceki host varsa durdurulur.
Stream<HostOlayi> hostBaslat({
  required String ad,
  required String parola,
  required bool upnp,
}) => RustLib.instance.api.crateApiAfudeskHostBaslat(
  ad: ad,
  parola: parola,
  upnp: upnp,
);

Future<void> hostKabul({required bool kontrol, required bool dosya}) => RustLib
    .instance
    .api
    .crateApiAfudeskHostKabul(kontrol: kontrol, dosya: dosya);

Future<void> hostRed() => RustLib.instance.api.crateApiAfudeskHostRed();

Future<void> hostKes() => RustLib.instance.api.crateApiAfudeskHostKes();

Future<void> hostDurdur() => RustLib.instance.api.crateApiAfudeskHostDurdur();

/// Koda bağlan. Her şey (hatalar dahil: `tur = "hata"`) `olaylar` akışından gelir.
/// Not: FRB akış fonksiyonunun Err dönüşü akışa değil yakalanmamış istisnaya gider;
/// bu yüzden hata olay olarak yazılır.
Stream<IzleyiciOlayi> izleyiciBaglan({
  required String kod,
  required String parola,
  required String ad,
}) => RustLib.instance.api.crateApiAfudeskIzleyiciBaglan(
  kod: kod,
  parola: parola,
  ad: ad,
);

/// Dart kareyi ekrana çizdiğinde çağırır.
void kareCizildi() => RustLib.instance.api.crateApiAfudeskKareCizildi();

Future<void> izleyiciGirdi({required GirdiOlayi g}) =>
    RustLib.instance.api.crateApiAfudeskIzleyiciGirdi(g: g);

/// Dosyayı karşı tarafa gönderir; ilerleme/sonuç izleyici akışına `tur = "dosya"` olarak gelir.
Future<void> izleyiciDosyaGonder({required String yol}) =>
    RustLib.instance.api.crateApiAfudeskIzleyiciDosyaGonder(yol: yol);

Future<void> izleyiciKapat() =>
    RustLib.instance.api.crateApiAfudeskIzleyiciKapat();

/// Girdi. `tur`: konum | fare | kaydir | tus | metin.
class GirdiOlayi {
  final String tur;
  final double x;
  final double y;

  /// fare: sol | sag | orta; tus: tuş adı.
  final String ad;
  final bool basili;
  final int dx;
  final int dy;
  final String metin;

  const GirdiOlayi({
    required this.tur,
    required this.x,
    required this.y,
    required this.ad,
    required this.basili,
    required this.dx,
    required this.dy,
    required this.metin,
  });

  static Future<GirdiOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskGirdiOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      x.hashCode ^
      y.hashCode ^
      ad.hashCode ^
      basili.hashCode ^
      dx.hashCode ^
      dy.hashCode ^
      metin.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GirdiOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          x == other.x &&
          y == other.y &&
          ad == other.ad &&
          basili == other.basili &&
          dx == other.dx &&
          dy == other.dy &&
          metin == other.metin;
}

/// Host olayı. `tur`: hazir | istek | baglandi | koptu | hata | dosya.
class HostOlayi {
  final String tur;
  final String kod;
  final String parola;
  final String erisim;
  final List<String> adresler;
  final String ad;
  final String metin;
  final bool kontrol;

  /// baglandi: dosya alma izni.
  final bool dosya;

  /// dosya: alınan dosyanın tam yolu.
  final String yol;

  const HostOlayi({
    required this.tur,
    required this.kod,
    required this.parola,
    required this.erisim,
    required this.adresler,
    required this.ad,
    required this.metin,
    required this.kontrol,
    required this.dosya,
    required this.yol,
  });

  static Future<HostOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskHostOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      kod.hashCode ^
      parola.hashCode ^
      erisim.hashCode ^
      adresler.hashCode ^
      ad.hashCode ^
      metin.hashCode ^
      kontrol.hashCode ^
      dosya.hashCode ^
      yol.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HostOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          kod == other.kod &&
          parola == other.parola &&
          erisim == other.erisim &&
          adresler == other.adresler &&
          ad == other.ad &&
          metin == other.metin &&
          kontrol == other.kontrol &&
          dosya == other.dosya &&
          yol == other.yol;
}

/// İzleyici olayı. `tur`: bekliyor | kabul | kare | istatistik | koptu | hata | dosya.
class IzleyiciOlayi {
  final String tur;
  final int rttMs;
  final int fps;
  final String ad;
  final String metin;
  final bool kontrol;
  final int genislik;
  final int yukseklik;
  final Uint8List rgba;

  /// kabul: dosya gönderme izni.
  final bool dosya;

  /// dosya: gönderilen/toplam bayt; `bitti` ise `metin` boşsa başarılı, doluysa hata.
  final BigInt gonderilen;
  final BigInt toplam;
  final bool bitti;

  const IzleyiciOlayi({
    required this.tur,
    required this.rttMs,
    required this.fps,
    required this.ad,
    required this.metin,
    required this.kontrol,
    required this.genislik,
    required this.yukseklik,
    required this.rgba,
    required this.dosya,
    required this.gonderilen,
    required this.toplam,
    required this.bitti,
  });

  static Future<IzleyiciOlayi> default_() =>
      RustLib.instance.api.crateApiAfudeskIzleyiciOlayiDefault();

  @override
  int get hashCode =>
      tur.hashCode ^
      rttMs.hashCode ^
      fps.hashCode ^
      ad.hashCode ^
      metin.hashCode ^
      kontrol.hashCode ^
      genislik.hashCode ^
      yukseklik.hashCode ^
      rgba.hashCode ^
      dosya.hashCode ^
      gonderilen.hashCode ^
      toplam.hashCode ^
      bitti.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IzleyiciOlayi &&
          runtimeType == other.runtimeType &&
          tur == other.tur &&
          rttMs == other.rttMs &&
          fps == other.fps &&
          ad == other.ad &&
          metin == other.metin &&
          kontrol == other.kontrol &&
          genislik == other.genislik &&
          yukseklik == other.yukseklik &&
          rgba == other.rgba &&
          dosya == other.dosya &&
          gonderilen == other.gonderilen &&
          toplam == other.toplam &&
          bitti == other.bitti;
}
